---
title: "Modellazione multilevel con componenti principali funzionali"
author: "Daniele Zago, Simon Mazzarolo, Silvia Brosolo, Emanuele Donà"
date: "2021-04-28"
output: 
    pdf_document:
        dev: png
        extra_dependencies: ["bm"]
        df_print: kable
        latex_engine: xelatex
---

```{r multilevel-base_setup, cache=FALSE, include=FALSE}
knitr::opts_chunk$set(cache=TRUE, engine.opts='-l', tidy=FALSE, fig.width=16, fig.height=10, dpi = 200)
knitr::knit_hooks$set(inline=function(x) prettyNum(round(x,2)))
setwd("~/Documents/git/progetto-iterazione/models/")
```

```{r libs, message=FALSE}
library(rstanarm)
library(bayesplot)
library(tidybayes)
library(ggplot2)
library(magrittr)
library(lme4)
library(dplyr)
library(gtools)
library(tidyr)
library(kableExtra)
```

```{r load}
load("comparison.Rdata")
load("fitStanFpcaFinal.Rdata")
```

```{r model}
png("cog_load.png", 2000, 1200, res = 150)
plot(fitStanFpcaFinal, plotfun = "dens", pars = "cog_loadCL6")
dev.off()
print(fitStanFpcaFinal)
posterior = as.data.frame(fitStanFpcaFinal)
```

```{r func}
get_posterior = function(posterior, fpc, syllable1, syllable2, fixed = "none", subject = NULL){
    # TODO: Docstring for get_posterior.
	#
    # @param posterior TODO
    # @param syllable1 TODO
    # @param syllable2 TODO
    # @param fixed TODO
    # @param subject TODO
	#
    # @return TODO

    # ---------- Estraggo coefficienti relativi a tutte le variabili che interessano --------- #
    cols = colnames(posterior)
    base = c("(Intercept)")
    PC1 = c("PC1", paste0("PC1:", "syllable", 1:2, c(syllable1, syllable2)))
    PC1 = PC1[PC1 %in% cols]
    PC2 = c("PC2", paste0("PC2:", "syllable", 1:2, c(syllable1, syllable2)))
    PC2 = PC2[PC2 %in% cols]
    PC3 = c("PC3", paste0("PC3:", "syllable", 1:2, c(syllable1, syllable2)))
    PC3 = PC3[PC3 %in% cols]
    PC4 = c("PC4", paste0("PC4:", "syllable", 1:2, c(syllable1, syllable2)))
    PC4 = PC4[PC4 %in% cols]
    
    if(fixed == "first"){
        # ---------- Calcolo posteriori delle curve baseline, che contiene fPC1 e tutte le var che non sono modificate dalle sillabe --------- #
        ref_PC1 = c("PC1", paste0("PC1:", "syllable1", syllable1))
        ref_PC1 = ref_PC1[ref_PC1 %in% cols]
        ref_PC2 = c("PC2", paste0("PC2:", "syllable1", syllable1))
        ref_PC2 = ref_PC2[ref_PC2 %in% cols]
        ref_PC3 = c("PC3", paste0("PC3:", "syllable1", syllable1))
        ref_PC3 = ref_PC3[ref_PC3 %in% cols]
        ref_PC4 = c("PC4", paste0("PC4:", "syllable1", syllable1))
        ref_PC4 = ref_PC4[ref_PC4 %in% cols]
        
        ref_PC1_beta = posterior[ , ref_PC1, drop=FALSE]
        ref_PC2_beta = posterior[ , ref_PC2, drop=FALSE]
        ref_PC3_beta = posterior[ , ref_PC3, drop=FALSE]
        ref_PC4_beta = posterior[ , ref_PC4, drop=FALSE]

        eigenf = fpca$phi
        
        PC1_ref = matrix(0, nrow = NROW(ref_PC1_beta), ncol = NROW(eigenf))
        for(cl in colnames(ref_PC1_beta)){
            PC1_ref = PC1_ref +
                ref_PC1_beta[ , cl ] %*% t(eigenf[ , 1 ])
        }
        PC2_ref = matrix(0, nrow = NROW(ref_PC2_beta), ncol = NROW(eigenf))
        for(cl in colnames(ref_PC2_beta)){
            PC2_ref = PC2_ref +
                ref_PC2_beta[ , cl ] %*% t(eigenf[ , 2 ])
        }

        PC3_ref = matrix(0, nrow = NROW(ref_PC3_beta), ncol = NROW(eigenf))
        for(cl in colnames(ref_PC3_beta)){
            PC3_ref = PC3_ref +
                ref_PC3_beta[ , cl ] %*% t(eigenf[ , 3 ])
        }
        PC4_ref = matrix(0, nrow = NROW(ref_PC4_beta), ncol = NROW(eigenf))
        for(cl in colnames(ref_PC4_beta)){
            PC4_ref = PC4_ref +
                ref_PC4_beta[ , cl ] %*% t(eigenf[ , 4 ])
        }

        ref_int = matrix(posterior[ , base], nrow = NROW(PC1_ref), ncol = NCOL(PC1_ref))
        PC_ref = ref_int + PC1_ref + PC2_ref + PC3_ref + PC4_ref

        # ---------- Calcolo scostamento delle fPC 2-4 dovuto al variare delle sillabe --------- #
        cols = colnames(posterior)
        PC1 = c(paste0("PC1:", "syllable", 2, syllable2))
        PC1 = PC1[PC1 %in% cols]
        PC2 = c(paste0("PC2:", "syllable", 2, syllable2))
        PC2 = PC2[PC2 %in% cols]
        PC3 = c(paste0("PC3:", "syllable", 2, syllable2))
        PC3 = PC3[PC3 %in% cols]
        PC4 = c(paste0("PC4:", "syllable", 2, syllable2))
        PC4 = PC4[PC4 %in% cols]

        PC1_beta = posterior[ , PC1, drop=FALSE]
        PC2_beta = posterior[ , PC2, drop=FALSE]
        PC3_beta = posterior[ , PC3, drop=FALSE]
        PC4_beta = posterior[ , PC4, drop=FALSE]

        PC1_syll = matrix(0, nrow = NROW(PC1_beta), ncol = NROW(eigenf))
        for(cl in colnames(PC1_beta)){
            PC1_syll = PC1_syll +
                PC1_beta[ , cl ] %*% t(eigenf[ , 1 ])
        }
        PC2_syll = matrix(0, nrow = NROW(PC2_beta), ncol = NROW(eigenf))
        for(cl in colnames(PC2_beta)){
            PC2_syll = PC2_syll +
                PC2_beta[ , cl ] %*% t(eigenf[ , 2 ])
        }

        PC3_syll = matrix(0, nrow = NROW(PC3_beta), ncol = NROW(eigenf))
        for(cl in colnames(PC3_beta)){
            PC3_syll = PC3_syll +
                PC3_beta[ , cl ] %*% t(eigenf[ , 3 ])
        }
        PC4_syll = matrix(0, nrow = NROW(PC4_beta), ncol = NROW(eigenf))
        for(cl in colnames(PC4_beta)){
            PC4_syll = PC4_syll +
                PC4_beta[ , cl ] %*% t(eigenf[ , 4 ])
        }
        PC_syll = PC1_syll + PC2_syll + PC3_syll + PC4_syll
        baseline = paste0(syllable1, ":T1")
    }
    
    if(fixed == "second"){
        # ---------- Calcolo posteriori delle curve baseline, che contiene fPC1 e tutte le var che non sono modificate dalle sillabe --------- #
        ref_PC1 = c("PC1", paste0("PC1:", "syllable2", syllable2))
        ref_PC1 = ref_PC1[ref_PC1 %in% cols]
        ref_PC2 = c("PC2", paste0("PC2:", "syllable2", syllable2))
        ref_PC2 = ref_PC2[ref_PC2 %in% cols]
        ref_PC3 = c("PC3", paste0("PC3:", "syllable2", syllable2))
        ref_PC3 = ref_PC3[ref_PC3 %in% cols]
        ref_PC4 = c("PC4", paste0("PC4:", "syllable2", syllable2))
        ref_PC4 = ref_PC4[ref_PC4 %in% cols]
        
        ref_PC1_beta = posterior[ , ref_PC1, drop=FALSE]
        ref_PC2_beta = posterior[ , ref_PC2, drop=FALSE]
        ref_PC3_beta = posterior[ , ref_PC3, drop=FALSE]
        ref_PC4_beta = posterior[ , ref_PC4, drop=FALSE]

        eigenf = fpca$phi
        
        PC1_ref = matrix(0, nrow = NROW(ref_PC1_beta), ncol = NROW(eigenf))
        for(cl in colnames(ref_PC1_beta)){
            PC1_ref = PC1_ref +
                ref_PC1_beta[ , cl ] %*% t(eigenf[ , 1 ])
        }
        PC2_ref = matrix(0, nrow = NROW(ref_PC2_beta), ncol = NROW(eigenf))
        for(cl in colnames(ref_PC2_beta)){
            PC2_ref = PC2_ref +
                ref_PC2_beta[ , cl ] %*% t(eigenf[ , 2 ])
        }

        PC3_ref = matrix(0, nrow = NROW(ref_PC3_beta), ncol = NROW(eigenf))
        for(cl in colnames(ref_PC3_beta)){
            PC3_ref = PC3_ref +
                ref_PC3_beta[ , cl ] %*% t(eigenf[ , 3 ])
        }
        PC4_ref = matrix(0, nrow = NROW(ref_PC4_beta), ncol = NROW(eigenf))
        for(cl in colnames(ref_PC4_beta)){
            PC4_ref = PC4_ref +
                ref_PC4_beta[ , cl ] %*% t(eigenf[ , 4 ])
        }

        ref_int = matrix(posterior[ , base], nrow = NROW(PC1_ref), ncol = NCOL(PC1_ref))
        PC_ref = ref_int + PC1_ref + PC2_ref + PC3_ref + PC4_ref

        # ---------- Calcolo scostamento delle fPC 2-4 dovuto al variare delle sillabe --------- #
        cols = colnames(posterior)
        PC1 = c(paste0("PC1:", "syllable", 1, syllable1))
        PC1 = PC1[PC1 %in% cols]
        PC2 = c(paste0("PC2:", "syllable", 1, syllable1))
        PC2 = PC2[PC2 %in% cols]
        PC3 = c(paste0("PC3:", "syllable", 1, syllable1))
        PC3 = PC3[PC3 %in% cols]
        PC4 = c(paste0("PC4:", "syllable", 1, syllable1))
        PC4 = PC4[PC4 %in% cols]

        PC1_beta = posterior[ , PC1, drop=FALSE]
        PC2_beta = posterior[ , PC2, drop=FALSE]
        PC3_beta = posterior[ , PC3, drop=FALSE]
        PC4_beta = posterior[ , PC4, drop=FALSE]

        PC1_syll = matrix(0, nrow = NROW(PC1_beta), ncol = NROW(eigenf))
        for(cl in colnames(PC1_beta)){
            PC1_syll = PC1_syll +
                PC1_beta[ , cl ] %*% t(eigenf[ , 1 ])
        }
        PC2_syll = matrix(0, nrow = NROW(PC2_beta), ncol = NROW(eigenf))
        for(cl in colnames(PC2_beta)){
            PC2_syll = PC2_syll +
                PC2_beta[ , cl ] %*% t(eigenf[ , 2 ])
        }

        PC3_syll = matrix(0, nrow = NROW(PC3_beta), ncol = NROW(eigenf))
        for(cl in colnames(PC3_beta)){
            PC3_syll = PC3_syll +
                PC3_beta[ , cl ] %*% t(eigenf[ , 3 ])
        }
        PC4_syll = matrix(0, nrow = NROW(PC4_beta), ncol = NROW(eigenf))
        for(cl in colnames(PC4_beta)){
            PC4_syll = PC4_syll +
                PC4_beta[ , cl ] %*% t(eigenf[ , 4 ])
        }
        PC_syll = PC1_syll + PC2_syll + PC3_syll + PC4_syll
        baseline = paste0("T1:", syllable2)
    }

    # else if(fixed == "none"){
    #     # ---------- Calcolo posteriori delle curve baseline, che contiene fPC1 e tutte le var che non sono modificate dalle sillabe --------- #
    #     base_post = posterior[ , base ]             # Intercetta
    #     PC1_beta = posterior[ , PC1, drop=FALSE]
    #     PC2_beta = posterior[ , PC2, drop=FALSE]
    #     PC3_beta = posterior[ , PC3, drop=FALSE]
    #     PC4_beta = posterior[ , PC4, drop=FALSE]
    #     eigenf = fpca$phi

    #     PC1_base = PC1_beta$PC1 %*% t(eigenf[ , 1 ]) 
    #     PC2_base = PC2_beta$PC2 %*% t(eigenf[ , 2 ]) 
    #     PC3_base = PC3_beta$PC3 %*% t(eigenf[ , 3 ]) 
    #     PC4_base = PC4_beta$PC4 %*% t(eigenf[ , 4 ]) 

    #     PC1_syll = matrix(0, nrow = NROW(PC1_base), ncol = NCOL(PC1_base))
    #     for(cl in colnames(PC1_beta)[-1]){
    #         PC1_syll = PC1_syll + PC1_beta[ , cl ] %*% t(eigenf[ , 1 ])
    #     }

    #     PC_base = matrix(base_post, nrow = NROW(PC1_base), ncol = NCOL(PC1_base)) +
    #         PC1_base + PC2_base + PC3_base + PC4_base + PC1_syll

    #     # ---------- Calcolo scostamento delle fPC 2-4 dovuto al variare delle sillabe --------- #

    #     if(NCOL(current1_post) == 0){
    #         current1_post = 0
    #     }
    #     current2_post = posterior[ , current2 ]
    #     if(NCOL(current2_post) == 0){
    #         current2_post = 0
    #     }

    #     PC2_syll = matrix(0, nrow = NROW(PC2_base), ncol = NCOL(PC2_base))
    #     for(cl in colnames(PC2_beta)[-1]){
    #         PC2_syll = PC2_syll + PC2_beta[ , cl ] %*% t(eigenf[ , 2 ])
    #     }
    #     PC3_syll = matrix(0, nrow = NROW(PC3_base), ncol = NCOL(PC3_base))
    #     for(cl in colnames(PC3_beta)[-1]){
    #         PC3_syll = PC3_syll + PC3_beta[ , cl ] %*% t(eigenf[ , 3 ])
    #     }
    #     PC4_syll = matrix(0, nrow = NROW(PC4_base), ncol = NCOL(PC4_base))
    #     for(cl in colnames(PC4_beta)[-1]){
    #         PC4_syll = PC4_syll + PC4_beta[ , cl ] %*% t(eigenf[ , 4 ])
    #     }

    #     PC_syll =  PC2_syll + PC3_syll + PC4_syll + 
    #         cbind(matrix(current1_post, nrow = NROW(PC1_syll), ncol = 10), matrix(0, nrow = NROW(PC1_syll), ncol = 10)) + 
    #         cbind(matrix(0, nrow = NROW(PC1_syll), ncol = 10), matrix(current2_post, nrow = NROW(PC1_syll), ncol = 10)) 

    #     baseline = "T1:T1"
    # }

    return(list("baseline" = PC_ref, "scostamento" = PC_syll,
                "syllable1" = syllable1, "syllable2" = syllable2, "ref" = baseline))
}

plot_posterior = function(post_fpca, ndraws = 4000, fixed = "both"){
    # TODO: Docstring for plot_posterior.
	#
    # @param post_fpca TODO
	#
    # @return TODO

    idx = sample(1:NROW(post_fpca$baseline), ndraws)
    baseline = post_fpca$baseline[idx, ]
    scostamento = post_fpca$scostamento[idx, ]

    if(fixed == "both"){
        par(mfrow = c(2, 1))
        matplot(t(baseline), type = "l", main = paste0("Baseline ", post_fpca$ref), col = "grey")
        lines(rowMeans(t(baseline)))
        matplot(t(scostamento), type = "l", main = paste0("Scostamento dovuto a ", post_fpca$syllable1, ":", post_fpca$syllable2), col = "grey")
        lines(rowMeans(t(scostamento)))
        par(mfrow = c(1,1))
    } else if (fixed == "first"){
        scostamento_plot = t(scostamento)[1:10, ]
        meanf = rowMeans(scostamento_plot)
        qtl = apply(scostamento_plot, 1, quantile, p=c(0.25, 0.975))
        df = data.frame(cbind(1:10, meanf, t(qtl)))
        colnames(df) = c("time", "mean", "lcl", "ucl")
        df %>%
            ggplot(aes(x = time))+
            geom_line(aes(y = mean), colour = "blue", alpha=0.9) + 
            geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2)
        par(mfrow = c(2, 1))
        matplot(t(baseline)[1:10, ], type = "l", main = paste0("baseline ", post_fpca$ref), col = "grey")
        lines(rowMeans(t(baseline))[1:10])
        scostamento_plot = t(scostamento)[1:10, ]
        meanf = rowMeans(scostamento_plot)
        qtl = apply(scostamento_plot, 1, quantile, p=c(0.25, 0.975))
        df = data.frame(cbind(1:10, meanf, t(qtl)))
        colnames(df) = c("time", "mean", "lcl", "ucl")
        df %>%
            ggplot(aes(x = time))+
            geom_line(aes(y = mean), colour = "blue", alpha=0.9) + 
            geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2)
    } else{
        par(mfrow = c(2, 1))
        matplot(11:20, t(baseline)[11:20, ], type = "l", main = paste0("Baseline ", post_fpca$ref), col = "grey")
        lines(11:20, rowMeans(t(baseline))[11:20])
        matplot(11:20, t(scostamento)[11:20, ], type = "l", main = paste0("Scostamento ", post_fpca$syllable2, " dovuto a ", post_fpca$syllable1, ":", post_fpca$syllable2), col = "grey")
        lines(11:20, rowMeans(t(scostamento))[11:20], col = "blue")
        par(mfrow = c(1,1))
    }
}
```

```{r grafici_posteriori}
post_fpca = get_posterior(posterior, fpca, "T1", "T1", fixed = "first")
p = recordPlot()
plot_posterior(post_fpca, fixed = "first")

png("first-t2.png", 2000, 1200, res = 150)
post_fpca = get_posterior(posterior, fpca, "T1", "T2", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
dev.off()

png("first-t3.png", 2000, 1200, res = 150)
post_fpca = get_posterior(posterior, fpca, "T1", "T3", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
dev.off()

png("first-t4.png", 2000, 1200, res = 150)
post_fpca = get_posterior(posterior, fpca, "T1", "T4", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
dev.off()

post_fpca = get_posterior(posterior, fpca, "T2", "T1", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
post_fpca = get_posterior(posterior, fpca, "T2", "T2", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
post_fpca = get_posterior(posterior, fpca, "T2", "T3", fixed = "first")
plot_posterior(post_fpca, fixed = "first")

png("first-t4.png", 2000, 1200, res = 150)
post_fpca = get_posterior(posterior, fpca, "T2", "T4", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
dev.off()

post_fpca = get_posterior(posterior, fpca, "T3", "T1", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
post_fpca = get_posterior(posterior, fpca, "T3", "T2", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
post_fpca = get_posterior(posterior, fpca, "T3", "T3", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
post_fpca = get_posterior(posterior, fpca, "T3", "T4", fixed = "first")
plot_posterior(post_fpca, fixed = "first")

post_fpca = get_posterior(posterior, fpca, "T4", "T1", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
post_fpca = get_posterior(posterior, fpca, "T4", "T2", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
post_fpca = get_posterior(posterior, fpca, "T4", "T3", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
post_fpca = get_posterior(posterior, fpca, "T4", "T4", fixed = "first")
plot_posterior(post_fpca, fixed = "first")
```

```{r grafici_posteriori2}
post_fpca = get_posterior(posterior, fpca, "T1", "T1", fixed = "second")
plot_posterior(post_fpca, fixed = "second")

png("second-t2.png", 2000, 1200, res = 150)
post_fpca = get_posterior(posterior, fpca, "T2", "T1", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
dev.off()

png("second-t3.png", 2000, 1200, res = 150)
post_fpca = get_posterior(posterior, fpca, "T3", "T1", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
dev.off()

png("second-t4.png", 2000, 1200, res = 150)
post_fpca = get_posterior(posterior, fpca, "T4", "T1", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
dev.off()

post_fpca = get_posterior(posterior, fpca, "T1", "T2", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
post_fpca = get_posterior(posterior, fpca, "T2", "T2", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
post_fpca = get_posterior(posterior, fpca, "T3", "T2", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
post_fpca = get_posterior(posterior, fpca, "T4", "T2", fixed = "second")
plot_posterior(post_fpca, fixed = "second")

post_fpca = get_posterior(posterior, fpca, "T1", "T3", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
post_fpca = get_posterior(posterior, fpca, "T2", "T3", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
post_fpca = get_posterior(posterior, fpca, "T3", "T3", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
post_fpca = get_posterior(posterior, fpca, "T4", "T3", fixed = "second")
plot_posterior(post_fpca, fixed = "second")

post_fpca = get_posterior(posterior, fpca, "T1", "T4", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
post_fpca = get_posterior(posterior, fpca, "T2", "T4", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
post_fpca = get_posterior(posterior, fpca, "T3", "T4", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
post_fpca = get_posterior(posterior, fpca, "T4", "T4", fixed = "second")
plot_posterior(post_fpca, fixed = "second")
```



# facciamo i maiali

```{r}
baseline1 <- get_posterior(posterior, fpca, "T1", "T1", fixed = "first")$baseline
baseline2 <- get_posterior(posterior, fpca, "T1", "T1", fixed = "second")$baseline
baseline <- cbind(baseline1[,1:10], baseline2[,11:20])

meanf = rowMeans(t(baseline))
qtl = apply(baseline, 2, quantile, p=c(0.25, 0.975))
df = data.frame(cbind(1:20, meanf, t(qtl)))
colnames(df) = c("time", "mean", "lcl", "ucl")
pbase <- df %>%
            ggplot(aes(x = time))+
                geom_line(aes(y = mean), colour = "blue", alpha=0.9) + 
                geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2) +
                labs(title = "Baseline: (T1, T1)")
pbase
```


## (T2, T2)

```{r}
scostamento <- cbind(get_posterior(posterior, fpca, "T1", "T2", fixed = "first")$scostamento[,1:10],
                     get_posterior(posterior, fpca, "T2", "T1", fixed = "second")$scostamento[,11:20])

meanf = rowMeans(t(scostamento))
qtl = apply(scostamento, 2, quantile, p=c(0.25, 0.975))
df = data.frame(cbind(1:20, meanf, t(qtl)))
colnames(df) = c("time", "mean", "lcl", "ucl")
p22 <- df %>%
        ggplot(aes(x = time))+
            geom_line(aes(y = mean), colour = "blue", alpha=0.9, ) + 
            geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2) +
            labs(title = "Mediazione di (T2, T2)")
p22
```
## (T2, T3)

```{r}
scostamento <- cbind(get_posterior(posterior, fpca, "T1", "T3", fixed = "first")$scostamento[,1:10],
                     get_posterior(posterior, fpca, "T2", "T1", fixed = "second")$scostamento[,11:20])

meanf = rowMeans(t(scostamento))
qtl = apply(scostamento, 2, quantile, p=c(0.25, 0.975))
df = data.frame(cbind(1:20, meanf, t(qtl)))
colnames(df) = c("time", "mean", "lcl", "ucl")
p23 <- df %>%
        ggplot(aes(x = time))+
            geom_line(aes(y = mean), colour = "blue", alpha=0.9) + 
            geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2) +
            labs(title = "Mediazione di (T2, T3)")
p23
```
## (T2, T4) (no mediazione)

```{r}
scostamento <- cbind(get_posterior(posterior, fpca, "T1", "T4", fixed = "first")$scostamento[,1:10],
                     get_posterior(posterior, fpca, "T2", "T1", fixed = "second")$scostamento[,11:20])


meanf = rowMeans(t(scostamento))
qtl = apply(scostamento, 2, quantile, p=c(0.25, 0.975))
df = data.frame(cbind(1:20, meanf, t(qtl)))
colnames(df) = c("time", "mean", "lcl", "ucl")
p24 <- df %>%
        ggplot(aes(x = time))+
            geom_line(aes(y = mean), colour = "blue", alpha=0.9) + 
            geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2) +
            labs(title = "Mediazione di (T2, T4)")
p24
```

## (T3, T2) (no mediazione)

```{r}
scostamento <- cbind(get_posterior(posterior, fpca, "T1", "T2", fixed = "first")$scostamento[,1:10],
                     get_posterior(posterior, fpca, "T3", "T1", fixed = "second")$scostamento[,11:20])


meanf = rowMeans(t(scostamento))
qtl = apply(scostamento, 2, quantile, p=c(0.25, 0.975))
df = data.frame(cbind(1:20, meanf, t(qtl)))
colnames(df) = c("time", "mean", "lcl", "ucl")
p32 <- df %>%
        ggplot(aes(x = time))+
            geom_line(aes(y = mean), colour = "blue", alpha=0.9) + 
            geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2) +
            labs(title = "Mediazione di (T3, T2)")
p32
```
## (T3, T3) (mediazione)

```{r}
scostamento <- cbind(get_posterior(posterior, fpca, "T1", "T3", fixed = "first")$scostamento[,1:10],
                     get_posterior(posterior, fpca, "T3", "T1", fixed = "second")$scostamento[,11:20])

meanf = rowMeans(t(scostamento))
qtl = apply(scostamento, 2, quantile, p=c(0.25, 0.975))
df = data.frame(cbind(1:20, meanf, t(qtl)))
colnames(df) = c("time", "mean", "lcl", "ucl")
p33 <- df %>%
        ggplot(aes(x = time))+
            geom_line(aes(y = mean), colour = "blue", alpha=0.9) + 
            geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2) +
            labs(title = "Mediazione di (T3, T3)")

p33
```
## (T3, T4) (no mediazione)

```{r}
scostamento <- cbind(get_posterior(posterior, fpca, "T1", "T4", fixed = "first")$scostamento[,1:10],
                     get_posterior(posterior, fpca, "T3", "T1", fixed = "second")$scostamento[,11:20])

meanf = rowMeans(t(scostamento))
qtl = apply(scostamento, 2, quantile, p=c(0.25, 0.975))
df = data.frame(cbind(1:20, meanf, t(qtl)))
colnames(df) = c("time", "mean", "lcl", "ucl")
p34 <- df %>%
        ggplot(aes(x = time))+
            geom_line(aes(y = mean), colour = "blue", alpha=0.9) + 
            geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2) +
            labs(title = "Mediazione di (T3, T4)")
p34
```

## (T4, T2) (no mediazione)

```{r}
scostamento <- cbind(get_posterior(posterior, fpca, "T1", "T2", fixed = "first")$scostamento[,1:10],
                     get_posterior(posterior, fpca, "T4", "T1", fixed = "second")$scostamento[,11:20])

meanf = rowMeans(t(scostamento))
qtl = apply(scostamento, 2, quantile, p=c(0.25, 0.975))
df = data.frame(cbind(1:20, meanf, t(qtl)))
colnames(df) = c("time", "mean", "lcl", "ucl")
p42 <- df %>%
        ggplot(aes(x = time))+
            geom_line(aes(y = mean), colour = "blue", alpha=0.9) + 
            geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2) +
            labs(title = "Mediazione di (T4, T2)")
p42
```

## (T4, T3) (mediazione)

```{r}
scostamento <- cbind(get_posterior(posterior, fpca, "T1", "T3", fixed = "first")$scostamento[,1:10],
                     get_posterior(posterior, fpca, "T4", "T1", fixed = "second")$scostamento[,11:20])


meanf = rowMeans(t(scostamento))
qtl = apply(scostamento, 2, quantile, p=c(0.25, 0.975))
df = data.frame(cbind(1:20, meanf, t(qtl)))
colnames(df) = c("time", "mean", "lcl", "ucl")
p43 <- df %>%
        ggplot(aes(x = time))+
            geom_line(aes(y = mean), colour = "blue", alpha=0.9) + 
            geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2) +
            labs(title = "Mediazione di (T4, T3)")

p43
```

## (T4, T4) (no mediazione)

```{r}
scostamento <- cbind(get_posterior(posterior, fpca, "T1", "T4", fixed = "first")$scostamento[,1:10],
                     get_posterior(posterior, fpca, "T4", "T1", fixed = "second")$scostamento[,11:20])

meanf = rowMeans(t(scostamento))
qtl = apply(scostamento, 2, quantile, p=c(0.25, 0.975))
df = data.frame(cbind(1:20, meanf, t(qtl)))
colnames(df) = c("time", "mean", "lcl", "ucl")
p44 <- df %>%
        ggplot(aes(x = time))+
            geom_line(aes(y = mean), colour = "blue", alpha=0.9) + 
            geom_ribbon(aes(ymin = lcl, ymax = ucl), colour = "darkgray", alpha=0.2) +
            labs(title = "Mediazione di (T4, T4)")
p44
```



```{r}
library(cowplot)



jpeg("mediazione_tutto.png", width = 800, height = 800)
# 2. Create the plot
plot_grid(p22, p23, p24,
          p32, p33, p34, 
          p42, p43, p44,
          ncol = 3)

# 3. Close the file
dev.off()
mediazione_tutto <- plot_grid(p22, p23, p24,
          p32, p33, p34, 
          p42, p43, p44,
          ncol = 3)
mediazione_tutto

ggsave(mediazione_tutto, filename = "mediazione_tutto.pdf", device = "pdf", width=16, height=10, dpi = 200
)
```

```{r}
mediazione_interessante <- plot_grid(p33, p43)
mediazione_interessante

jpeg("mediazione_interessante.png", width = 800, height = 500)
# 2. Create the plot
plot_grid(p33, p43)

# 3. Close the file
dev.off()


```



## BOh rob-e

```{r}
baseline_matrix <- matrix(NA, ncol = 8, nrow = 16)
colnames(baseline_matrix) <- as.factor(7:14)
k = 1

baseline_comune <- cbind(get_posterior(posterior, fpca, "T1", "T1", fixed = "first")$baseline[,7:10],
                        get_posterior(posterior, fpca, "T1", "T1", fixed = "second")$baseline[,11:14])

for(i in c("T1", "T2", "T3", "T4")){
    for(j in c("T1", "T2", "T3", "T4")){
        cat(paste(i, j, sep = "-"), "\n")
        baseline <- cbind(get_posterior(posterior, fpca, "T1", j, fixed = "first")$scostamento[,7:10],
                        get_posterior(posterior, fpca, i, "T1", fixed = "second")$scostamento[,11:14])
        baseline_matrix[k,] <- rowMeans(t(baseline + baseline_comune))
        k = k + 1
    }
}
plot(colMeans(baseline_matrix), type = "l", main = "Media della parte centrale di ogni combinazione di sillabe", ylab = "f0")

par(mfrow = c(4,4))
for(i in 1:nrow(baseline_matrix)){
    plot(7:14, baseline_matrix[i,], col = i, type = "l", xlab = "tempo", ylab = "", ylim = c(175, 275))
}
```

